# frozen_string_literal: true

module Dummy
  module TailwindGemSources
    module_function

    def css
      lines = ["/* Generated by rake tailwindcss:inject_gem_sources — do not edit. */"]
      source_directories.each do |directory|
        lines << %(@source "#{directory}";)
      end
      "#{lines.join("\n")}\n"
    end

    def source_directories
      [
        engine_path(FlatPack, "app/components"),
        engine_path(RecordingStudioAdmin, "app/views"),
        engine_path(RecordingStudioAdmin, "app/components"),
        engine_path(RecordingStudio, "app/views"),
        engine_path(RecordingStudioUser, "app/views"),
        engine_path(RecordingStudioUser, "app/components"),
        engine_path(RecordingStudioAttachable, "app/views"),
        engine_path(RecordingStudioNotifications, "app/views"),
        engine_path(RecordingStudioNotificationsEmail, "app/views"),
        engine_path(RecordingStudioNotificationsPush, "app/views")
      ].compact
    end

    def engine_path(mod, relative)
      return unless Object.const_defined?(mod.name) && mod.const_defined?(:Engine)

      path = mod::Engine.root.join(relative)
      path.to_s if path.exist?
    end
  end
end
