# frozen_string_literal: true

# Tailwind cannot interpolate Ruby, and gem paths differ between machines and
# deployments, so the @source lines for the views and components that Users and
# its dependencies ship are written out before every build instead of being
# committed with one machine's paths baked in.
namespace :tailwindcss do
  desc "Write Tailwind @source lines for RecordingStudioUsers gem templates"
  task :recording_studio_users_sources do
    gems = %w[
      recording_studio_users flat_pack recording_studio
      recording_studio_accessible recording_studio_root_switchable
    ]
    globs = { "app/views" => "**/*.erb", "app/components" => "**/*.{rb,erb}" }

    lines = gems.flat_map do |gem_name|
      spec = Gem.loaded_specs[gem_name] || Gem::Specification.find_all_by_name(gem_name).first
      next [] unless spec

      globs.filter_map do |directory, glob|
        path = File.join(spec.gem_dir, directory)
        %(@source "#{path}/#{glob}";) if File.directory?(path)
      end
    end

    header = "/* Generated by rails tailwindcss:recording_studio_users_sources. Do not edit or commit. */"
    Rails.root.join("app/assets/tailwind/recording_studio_users_sources.css")
         .write([header, *lines, ""].join("\n"))
  end
end

task "tailwindcss:build" => "tailwindcss:recording_studio_users_sources"
task "tailwindcss:watch" => "tailwindcss:recording_studio_users_sources"
